# Generated by Django 4.2.3 on 2023-07-31 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='slug',
            field=models.SlugField(default='raufmasoumi', max_length=100),
            preserve_default=False,
        ),
    ]
