# Generated by Django 4.2.4 on 2023-10-12 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasklists', '0002_alter_tasklist_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='is_default',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
