# Generated by Django 4.2.4 on 2023-10-16 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasklists', '0003_tasklist_is_default'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasklist',
            options={'ordering': ['-created_at', 'title'], 'permissions': [('default_tasklist', 'Can change default task list')]},
        ),
    ]
