# Generated by Django 4.2.7 on 2024-02-21 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasklists', '0004_alter_tasklist_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskListTaskPriority',
        ),
    ]
