# Generated by Django 4.2.3 on 2023-08-03 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listtaskpriority',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='done_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
