# Generated by Django 4.2.3 on 2023-08-05 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_listtaskpriority_number_alter_task_done_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='lists', to='tasks.task'),
        ),
    ]
