# Generated by Django 4.2.4 on 2023-08-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_task_id_alter_tasklist_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='tasklists', to='tasks.task'),
        ),
    ]
