# Generated by Django 4.2.4 on 2023-10-09 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_remove_tasklist_tasks_remove_tasklist_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_daily',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
